name: snakemake_savont
channels:
  - bioconda
  - conda-forge
dependencies:
  - snakemake=9.16.3
  - snakemake-executor-plugin-slurm=2.2.0
  - snakedeploy=0.16.0
  - snakefmt=0.11.4
  - gzip=1.13
  - cutadapt=5.2-0
  - usearch=11.0.667
  - savont=0.3.2
