# This file is for various variables used throughout the workflow.
# See a description of each setting in the config/README.md file.
input_dir: ".test/nanopore_run_xyz123/fastq_pass"
output_dir: "output"
tmp_dir: "tmp"
log_dir: "logs"
savont_asv_args: "--minimum-base-quality 25 --quality-value-cutoff 98 --min-read-length 400 --max-read-length 700"
classify_sintax: True
db_sintax: ".test/db_sintax.fa"
classify_sintax_args: "-strand both -sintax_cutoff 0.8"
classify_savont: True
classify_savont_db: "silva"
classify_savont_db_download_dir: "./databases"
classify_savont_args: ""
max_threads: 32
sample_sep: "_"
cutadapt_args: "-g AGRGTTYGATYMTGGCTCAG...GTTTGGCACCTCGATGTCG --revcomp --discard-untrimmed"
rarefy_abund_table: False
rarefy_sample_size: 2000
